kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv-volume
  namespace: mysql-namespace
  labels:
    type: local
spec:
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/projects/mysql/volume"

