
# This mysql service will be headless service

kind: Service
apiVersion: v1
metadata:
  name: mysql-service
  namespace: mysql-namespace
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      name: mysql
      port: 3306
      targetPort: 3306
  clusterIP: None
