kind: Pod
apiVersion: v1
metadata:
  name: init-test
  namespace: pods-namespace

spec:
  initContainers:
    - name: init-container
      image: busybox:latest
      command: ["sh", "-c", "echo 'Initilization started...'; sleep 10; echo 'Initilization completed.'"]


  containers:
    - name: main-container
      image: busybox:latest
      command: ["sh", "-c", "echo 'Main container started'"]
